# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'DevOps-002'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: 'Virtual Machine/vminit.sh'
    arguments: '1 TestRG'
    addSpnToEnvironment: true

- task: AzureCLI@2
  inputs:
    azureSubscription: 'DevOps-002'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az group delete -n TestRG -y'